name: on-pr

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - 'renovate.json'
      - ".github/workflows/**"
      - ".gitops/**"
      - "apis/**"
      - "examples/**"
      - "tests/**"
      - "functions/**"
      - "upbound.yaml"

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v3.0.0
    with:
      examples: |
        [
          { "example": "examples/fluxgitopsstacks/minimal.yaml" },
          { "example": "examples/fluxgitopsstacks/standard.yaml" },
          { "example": "examples/fluxgitopsstacks/nodepool.yaml" },
          { "example": "examples/fluxgitopsstacks/standard.yaml", "observed_resources": "examples/test/mocks/observed-resources/standard/steps/1/" },
          { "example": "examples/fluxgitopsstacks/standard.yaml", "observed_resources": "examples/test/mocks/observed-resources/standard/steps/2/" },
          { "example": "examples/fluxgitopsstacks/eso.yaml" },
          { "example": "examples/fluxgitopsstacks/eso.yaml", "observed_resources": "examples/test/mocks/observed-resources/eso/steps/1/" },
          { "example": "examples/fluxgitopsstacks/eso.yaml", "observed_resources": "examples/test/mocks/observed-resources/eso/steps/2/" },
          { "example": "examples/fluxgitopsstacks/eso.yaml", "observed_resources": "examples/test/mocks/observed-resources/eso/steps/3/" }
        ]
      api_path: apis/fluxgitopsstacks
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v3.0.0

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v3.0.0
    with:
      github: true
      gh-app-id: "2650923"
      gh-owner: ${{ github.repository_owner }}
    secrets:
      GH_APP_KEY: ${{ secrets.GH_APP_KEY }}

  publish:
    needs:
      - validate
      - test
    uses: unbounded-tech/workflows-crossplane/.github/workflows/publish.yaml@v3.0.0
    secrets: inherit
    with:
      tag: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
